[build]
  base = "tapes.dev"
  command = "npm run build"
  publish = "dist"
  # Skip build if tapes.dev folder hasn't changed
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- ."

[build.environment]
  NODE_VERSION = "20"

# Deploy previews for PRs
[context.deploy-preview]
  command = "npm run build"

# Branch deploys
[context.branch-deploy]
  command = "npm run build"
